### PR TITLE
Dev/new build commands

### PR DESCRIPTION
**Pull request by ktaletsk**
This PR adds new build commands to labextension with an aim to later create [prebuilt extension](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#overview-of-extensions)

### CODE REVIEW

**Comment by ktaletsk** [comment]
Currently trying to solve the issue where `jupyter labextension build` [crashes](https://github.com/ktaletsk/jupyterlab-latex/runs/3024694338?check_suite_focus=true#step:9:116) with heap out of memory error.

**Comment by bollwyvl** [comment]
Right, so as mentioned on gitter: try turning off minimization, which can save a lot of work:

```json
"jupyterlab": {
  "webpackConfig": "./webpack.config.js"
}
```

In said `webpack,config.js`:

```js
module.exports = {
  optimization: {
    minimize: false,
  },
};
```

Further, in `pdf.ts`: try changing the imports to use `!!url-loader!pdf.js/build/pdf.min.js` (or `!!file-loader`, i never remember which): you don't want `webpack` to even _look_ at those files... there is also the [assets module](https://webpack.js.org/guides/asset-modules/) which can force it to do even _less_ work.

**Comment by ktaletsk** [comment]
Thanks for the suggestions @bollwyvl. I am not entirely sure how to use `!!url-loader!pdf.js/build/pdf.min.js`, so I tried the following changes:
1. Prepend import paths with `!!url-loader` or `!!file-loader`
```
      import(
        /* webpackChunkName: "pdfjs" */ /* webpackMode: "lazy" */ '!!file-loader!pdfjs-dist/webpack' as any
      ),
      import(
        /* webpackChunkName: "pdfjs" */ /* webpackMode: "lazy" */ '!!file-loader!pdfjs-dist/web/pdf_viewer' as any
      ),
      import(
        /* webpackChunkName: "pdfjs" */ /* webpackMode: "lazy" */ '!!file-loader!pdfjs-dist/web/pdf_viewer.css' as any
      )
```
That helps with compilation issue, but at the runtime I get `Uncaught (in promise) TypeError: pdfjsLib.PDFViewer is not a constructor` at https://github.com/ktaletsk/jupyterlab-latex/blob/666b6b4da7d70f02ca840cd469c69ee646430546/src/pdf.ts#L76


2. I tried to import `pdfjs-dist/build/pdf` instead of `pdfjs-dist/webpack`:
```
export function ensurePDFJS(): Promise<any> {
    pdfjsLoaded = Promise.all([
      import( 
        /* webpackChunkName: "pdfjs" */ /* webpackMode: "lazy" */ 'pdfjs-dist/build/pdf' as any
      ),
      import(
        /* webpackChunkName: "pdfjs" */ /* webpackMode: "lazy" */ 'pdfjs-dist/build/pdf.worker.entry' as any
      ),
      import(
        /* webpackChunkName: "pdfjs" */ /* webpackMode: "lazy" */ 'pdfjs-dist/web/pdf_viewer' as any
      ),
      import(
        /* webpackChunkName: "pdfjs" */ /* webpackMode: "lazy" */ 'pdfjs-dist/web/pdf_viewer.css' as any
      )
    ])
      .then(([lib, worker, viewer]) => ({ ...lib, ...worker, ...viewer }))
      .catch(err => console.error(err));
    return pdfjsLoaded;
  }
```
and got the runtime error: `Uncaught (in promise) TypeError: Cannot read property 'dispatch' of undefined
    at pdf_viewer.js:5915`

It's not clear to me, at which direction to proceed with this

**Comment by ktaletsk** [comment]
Oops, the issue 2 was actually due to updated version of pdfjs=2.8.335 I used locally. I rolled it back to 2.0.943 and it all works: both build and runtime are fine.

**Comment by ktaletsk** [comment]
Things are looking good, merging

**Pull request merged**
